on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - '**.css'
      - '**.js'
      - 'assets/**'

  pull_request:
    branches:
      - main
    paths:
      - 'index.html'
      - '**.css'
      - '**.js'
      - 'assets/**'
